name: Build, push, and deploy to q2

on:
  push:
    branches: brreg-stub-test

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/brreg-stub:${{ github.sha }}

jobs:
  build:
    name: Bygg app/image, push til github, deploy til q2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Bygg med maven
        run: mvn -B --no-transfer-progress package
      - name: Build and push Docker container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy to nais q2 namespace
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais_brreg-stub-test.yaml
